--[[
* XIUI Module Settings Defaults
* Internal module settings (dimensions, fonts, positions, etc.)
* These are not user-configurable - they define the base layout for each module
]]--

local gdi = require('submodules.gdifonts.include');

local M = {};

-- Create the module defaults table
-- This becomes gAdjustedSettings after applying global font settings
function M.createModuleDefaults()
    return T{
        -- global settings
        currentPatchVer = 2,
        tpEmptyColor = 0xFF9acce8,
        tpFullColor = 0xFF2fa9ff,
        mpColor = 0xFFdef2db,

        -- settings for the targetbar
        targetBarSettings = T{
            -- Damage interpolation
            hitInterpolationDecayPercentPerSecond = 150,
            hitDelayDuration = 0.5,
            hitFlashDuration = 0.4,

            -- Everything else
            barWidth = 500,
            barHeight = 18,
            totBarHeight = 14,
            totBarOffset = -1,
            textScale = 1.2,
            cornerOffset = 5,
            nameXOffset = 12,
            nameYOffset = 9,
            iconSize = 22,
            arrowSize = 30,
            maxIconColumns = 12,
            topTextYOffset = 6,
            topTextXOffset = 5,
            bottomTextYOffset = 0,
            bottomTextXOffset = 15,
            -- Buff/Debuff positioning
            buffsOffsetY = 4,
            -- Cast bar positioning and scaling
            castBarOffsetY = 6,
            castBarOffsetX = 12,
            castBarWidth = 500,  -- Base width (will be adjusted by scale and inset)
            name_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            totName_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            distance_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 11,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            percent_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 11,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            cast_font_settings = T{
                font_alignment = gdi.Alignment.Center,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFAA00,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for the playerbar
        playerBarSettings = T{
            -- Damage interpolation
            hitInterpolationDecayPercentPerSecond = 150,
            hitDelayDuration = 0.5,
            hitFlashDuration = 0.4,
            barWidth = 500,
            barSpacing = 10,
            barHeight = 20,
            textYOffset = -1,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 15,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for enemy list
        enemyListSettings = T{
            barWidth = 125,
            barHeight = 10,
            textScale = 1,
            entrySpacing = 1,
            bgPadding = 7,
            bgTopPadding = -3,
            maxIcons = 5,
            iconSize = 18,
            debuffOffsetX = -10,
            debuffOffsetY = 0,
            name_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            distance_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 8,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            percent_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 8,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            target_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 8,
                font_color = 0xFFFFAA00,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            prim_data = {
                texture_offset_x= 0.0,
                texture_offset_y= 0.0,
                border_visible  = false,
                border_flags    = FontBorderFlags.None,
                border_sizes    = '0,0,0,0',
                visible         = false,
                position_x      = 0,
                position_y      = 0,
                can_focus       = true,
                locked          = false,
                lockedz         = false,
                scale_x         = 1.0,
                scale_y         = 1.0,
                width           = 0.0,
                height          = 0.0,
                color           = 0xFFFFFFFF,
            },
        },

        -- settings for the exp bar
        expBarSettings = T{
            barWidth = 550,
            barHeight = 12,
            textOffsetY = 4,
            -- Individual text offsets (applied from user settings)
            jobTextOffsetX = 0,
            jobTextOffsetY = 0,
            expTextOffsetX = 0,
            expTextOffsetY = 0,
            percentTextOffsetX = 0,
            percentTextOffsetY = 0,
            job_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 11,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            exp_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 11,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            percent_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 8,
                font_color = 0xFFFFFF00,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for gil tracker
        gilTrackerSettings = T{
            iconScale = 30,
            font_settings = T{
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        inventoryTrackerSettings = T{
            columnCount = 5,
            rowCount = 6,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        satchelTrackerSettings = T{
            columnCount = 5,
            rowCount = 6,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        lockerTrackerSettings = T{
            columnCount = 5,
            rowCount = 6,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        safeTrackerSettings = T{
            columnCount = 5,
            rowCount = 6,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        storageTrackerSettings = T{
            columnCount = 5,
            rowCount = 6,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        wardrobeTrackerSettings = T{
            columnCount = 10,
            rowCount = 8,
            dotRadius = 5,
            dotSpacing = 1,
            groupSpacing = 8,
            textOffsetY = -3,
            font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for mob info
        mobInfoSettings = T{
            iconSize = 20,
            iconSpacing = 2,
            rowSpacing = 4,
            maxIconsPerRow = 10,
            level_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        partyListSettings = T{
            -- Damage interpolation
            hitInterpolationDecayPercentPerSecond = 150,
            hitDelayDuration = 0.5,
            hitFlashDuration = 0.4,
            hpBarWidth = 150,
            tpBarWidth = 100,
            mpBarWidth = 100,
            barHeight = 20,
            barSpacing = 8,

            nameTextOffsetX = 1,
            nameTextOffsetY = 0,
            hpTextOffsetX = -2,
            hpTextOffsetY = -1,
            mpTextOffsetX = -2,
            mpTextOffsetY = -1,
            tpTextOffsetX = -2,
            tpTextOffsetY = -1,

            borderSize = 21,
            bgPadding = 4,
            bgPaddingY = 10,
            bgOffset = 1,

            cursorPaddingX1 = 8,
            cursorPaddingX2 = 8,
            cursorPaddingY1 = 7,
            cursorPaddingY2 = 10,
            dotRadius = 3,

            arrowSize = 1,

            subtargetArrowTint = 0xFFfdd017,
            targetArrowTint = 0xFFFFFFFF,

            iconSize = 22,
            maxIconColumns = 6,
            buffOffset = 10,
            xivBuffOffsetY = 1,
            statusOffsetX = 0,
            statusOffsetY = 0,
            entrySpacing = 8,
            expandHeight = false,
            alignBottom = false,
            minRows = 1,

            hp_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            mp_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            tp_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            name_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 13,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            title_font_settings = T{
                font_alignment = gdi.Alignment.None,
                font_family = 'Consolas',
                font_height = 14,
                font_color = 0xFFC5CFDC,
                font_flags = gdi.FontFlags.Italic,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            prim_data = {
                texture_offset_x= 0.0,
                texture_offset_y= 0.0,
                border_visible  = false,
                border_flags    = FontBorderFlags.None,
                border_sizes    = '0,0,0,0',
                visible         = true,
                position_x      = 0,
                position_y      = 0,
                can_focus       = false,
                locked          = true,
                lockedz         = true,
                scale_x         = 1.0,
                scale_y         = 1.0,
                width           = 0.0,
                height          = 0.0,
            },
        },

        castBarSettings = T{
            barWidth = 500,
            barHeight = 20,
            spellOffsetY = 2,
            percentOffsetY = 2,
            percentOffsetX = -10,
            spell_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 15,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            percent_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 15,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for cast cost
        castCostSettings = T{
            minWidth = 100,
            alignBottom = false,
            showCooldown = true,
            barScaleY = 1.0,
            bgPadding = 8,
            bgPaddingY = 8,
            borderSize = 21,
            bgOffset = 1,
            bgScale = 1.0,
            borderScale = 1.0,
            backgroundTheme = 'Window1',
            backgroundOpacity = 1.0,
            borderOpacity = 1.0,
            showName = true,
            showMpCost = true,
            showRecast = true,
            name_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            cost_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFD4FF97,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            time_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFCCCCCC,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            recast_font_settings = T{
                font_alignment = gdi.Alignment.Right,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            cooldown_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFF44CC44,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            prim_data = T{
                visible = false,
                can_focus = false,
                locked = true,
                width = 100,
                height = 100,
            },
        },

        -- settings for pet bar
        petBarSettings = T{
            barWidth = 150,
            barHeight = 12,
            barSpacing = 4,
            bgPadding = 8,
            bgPaddingY = 8,
            bgOffset = 1,
            bgScale = 1.0,
            borderScale = 1.0,
            borderSize = 21,
            -- HP interpolation settings
            hitInterpolationDecayPercentPerSecond = 150,
            hitDelayDuration = 0.5,
            hitFlashDuration = 0.4,
            prim_data = T{
                visible = false,
                can_focus = false,
                locked = true,
                width = 100,
                height = 100,
            },
            name_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            distance_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            vitals_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            timer_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFF00,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for notifications
        notificationsSettings = T{
            maxVisible = 10,
            spacing = 8,
            width = 280,
            iconSize = 32,
            bgPadding = 8,
            enterDuration = 0.3,
            exitDuration = 0.2,
            font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 12,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            title_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 14,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.Bold,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

        -- settings for treasure pool module
        treasurePoolSettings = T{
            font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 10,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.None,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
            title_font_settings = T{
                font_alignment = gdi.Alignment.Left,
                font_family = 'Consolas',
                font_height = 14,
                font_color = 0xFFFFFFFF,
                font_flags = gdi.FontFlags.Bold,
                outline_color = 0xFF000000,
                outline_width = 2,
            },
        },

    };
end

return M;
